### ISSUE TITLE
Merge more libraries on remote server

### ISSUE THREAD

**Issue by robooo** [robotframework/PythonRemoteServer#46]
Can't figure out how to merge more libraries on remote server side.

Found this discussion: https://groups.google.com/forum/#!topic/robotframework-users/ESMmd11z3b8
but the errors are the same. 

```
Traceback (most recent call last):
  File "frankenlib.py", line 92, in <module>
    RobotRemoteServer(FrankenLib(), *sys.argv[1:])
  File "C:\Python27\lib\site-packages\robotremoteserver.py", line 73, in __init__
    self._library = RemoteLibraryFactory(library)
  File "C:\Python27\lib\site-packages\robotremoteserver.py", line 256, in RemoteLibraryFactory
    run_keyword = dynamic_method(library, 'run_keyword')
  File "C:\Python27\lib\site-packages\robotremoteserver.py", line 266, in dynamic_method
    method = getattr(library, name, None)
  File "frankenlib.py", line 50, in __getattr__
    module_num = self._modulenames.index(module)
ValueError: 'run' is not in list
```

**Comment by robooo** [comment]
should works with https://github.com/robotframework/PythonRemoteServer/issues/19
